apiVersion: v1
kind: Service
metadata:
  name: cloudops-ai-assistant-service
spec:
  selector:
    app: cloudops-ai-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP